// キミキー 楽曲データ 100曲版
// ※音域は「音域ベースの目安」です。
// 音源・歌唱方法・裏声を含むかなどによって実際の音域は異なる場合があります。

const NOTE_INDEX = {
  C: 0,
  'C#': 1,
  D: 2,
  'D#': 3,
  E: 4,
  F: 5,
  'F#': 6,
  G: 7,
  'G#': 8,
  A: 9,
  'A#': 10,
  B: 11,
}

function pitchLabelToMidi(label) {
  const match =
    label.match(
      /^(low|mid1|mid2|hi)([A-G](?:#)?)$/
    )

  if (!match) {
    throw new Error(
      `Unknown pitch label: ${label}`
    )
  }

  const [, band, note] = match

  const bandStartMidi = {
    low: 33,  // A1
    mid1: 45, // A2
    mid2: 57, // A3
    hi: 69,   // A4
  }

  const offsetFromA = {
    A: 0,
    'A#': 1,
    B: 2,
    C: 3,
    'C#': 4,
    D: 5,
    'D#': 6,
    E: 7,
    F: 8,
    'F#': 9,
    G: 10,
    'G#': 11,
  }

  return (
    bandStartMidi[band] +
    offsetFromA[note]
  )
}

const RAW_SONGS = [
  {
    title: 'Brand New',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiE',
    gender: 'hard',
  },
  {
    title: 'ライラック',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1E',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: '好きすぎて滅!',
    artist: 'M!LK',
    lowLabel: 'mid1B',
    highLabel: 'hiC#',
    gender: 'hard',
  },
  {
    title: 'IRIS OUT',
    artist: '米津玄師',
    lowLabel: 'mid1A#',
    highLabel: 'hiA',
    gender: 'male',
  },
  {
    title: '青と夏',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'lowF',
    highLabel: 'hiE',
    gender: 'hard',
  },
  {
    title: 'Blue Jeans',
    artist: 'HANA',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'hard',
  },
  {
    title: '恋、はじめました。',
    artist: '=LOVE',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'Soranji',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C',
    highLabel: 'hiF#',
    gender: 'hard',
  },
  {
    title: 'lulu.',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C#',
    highLabel: 'hiD#',
    gender: 'hard',
  },
  {
    title: 'アイドルパワー',
    artist: 'M!LK',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
  },

  {
    title: 'HAPPY BIRTHDAY',
    artist: 'back number',
    lowLabel: 'lowG#',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'ケセラセラ',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiF',
    gender: 'hard',
  },
  {
    title: 'I Got Your Back',
    artist: 'ILLIT & HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: 'ダーリン',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'ROSE',
    artist: 'HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'ブルーアンバー',
    artist: 'back number',
    lowLabel: 'mid1A#',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: '僕のこと',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiD#',
    gender: 'male',
  },
  {
    title: 'マイオンリー',
    artist: 'SixTONES',
    lowLabel: 'mid1C#',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: '水平線',
    artist: 'back number',
    lowLabel: 'mid1C#',
    highLabel: 'hiC',
    gender: 'male',
  },
  {
    title: 'ヒロイン',
    artist: 'back number',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
  },

  {
    title: 'Magic',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C#',
    highLabel: 'hiF',
    gender: 'hard',
  },
  {
    title: '怪獣',
    artist: 'サカナクション',
    lowLabel: 'mid1F',
    highLabel: 'hiB',
    gender: 'both',
  },
  {
    title: '115万キロのフィルム',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'hard',
  },
  {
    title: 'ダンスホール',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid2A',
    highLabel: 'hiF#',
    gender: 'female',
  },
  {
    title: 'Pretender',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'hard',
  },
  {
    title: 'AIZO',
    artist: 'King Gnu',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'ブルーアンビエンス (feat. asmi)',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'BAD',
    artist: 'ATEEZ',
    lowLabel: 'mid1F#',
    highLabel: 'hiC',
    gender: 'both',
  },
  {
    title: 'BPM (feat. KREVA)',
    artist: 'Kvi Baba',
    lowLabel: 'mid1D',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: 'Automatic',
    artist: '宇多田ヒカル',
    lowLabel: 'mid1F#',
    highLabel: 'hiE',
    gender: 'female',
  },

  {
    title: 'インディゴ地平線',
    artist: 'スピッツ',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'Subtitle',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'hard',
  },
  {
    title: 'StaRt',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1F#',
    highLabel: 'hiB',
    gender: 'both',
  },
  {
    title: 'Bad Girl',
    artist: 'HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'female',
  },
  {
    title: '波乗りジョニー',
    artist: '桑田佳祐',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'インフェルノ',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1B',
    highLabel: 'hiD#',
    gender: 'male',
  },
  {
    title: '夜に駆ける',
    artist: 'YOASOBI',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'きらり',
    artist: '藤井風',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: '劇薬中毒',
    artist: '=LOVE',
    lowLabel: 'mid2A',
    highLabel: 'hiC#',
    gender: 'female',
  },
  {
    title: 'SAD SONG',
    artist: 'ちゃんみな',
    lowLabel: 'mid1F',
    highLabel: 'hiD',
    gender: 'female',
  },

  {
    title: 'ドライフラワー',
    artist: '優里',
    lowLabel: 'lowF',
    highLabel: 'hiC',
    gender: 'male',
  },
  {
    title: 'Never Grow Up',
    artist: 'ちゃんみな',
    lowLabel: 'mid1F',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'ハレンチ',
    artist: 'ちゃんみな',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'クスシキ',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1E',
    highLabel: 'hiF',
    gender: 'male',
  },
  {
    title: 'Love so sweet',
    artist: '嵐',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
  },
  {
    title: '群青',
    artist: 'YOASOBI',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'Tiger',
    artist: 'HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'イエスタデイ',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'hard',
  },
  {
    title: '今夜このまま',
    artist: 'あいみょん',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'JANE DOE',
    artist: '米津玄師 & 宇多田ヒカル',
    lowLabel: 'mid1C',
    highLabel: 'hiD#',
    gender: 'hard',
  },

  {
    title: 'NON STOP',
    artist: 'HANA',
    lowLabel: 'mid1F#',
    highLabel: 'hiA#',
    gender: 'both',
  },
  {
    title: 'ロマンチシズム',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C',
    highLabel: 'hiD#',
    gender: 'male',
  },
  {
    title: '怪盗',
    artist: 'back number',
    lowLabel: 'mid1C#',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'Golden',
    artist: 'HUNTR/X',
    lowLabel: 'mid1D',
    highLabel: 'hiF#',
    gender: 'hard',
  },
  {
    title: 'KISS N TELL',
    artist: 'aespa',
    lowLabel: 'mid1G#',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: '晴々',
    artist: '緑黄色社会',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'Blue Shining Star',
    artist: 'アイナ・ジ・エンド',
    lowLabel: 'mid1B',
    highLabel: 'hiE',
    gender: 'hard',
  },
  {
    title: 'グッタイム',
    artist: 'Snow Man',
    lowLabel: 'mid1F',
    highLabel: 'hiC',
    gender: 'both',
  },
  {
    title: 'イケナイ太陽',
    artist: 'ORANGE RANGE',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: '小さな恋のうた',
    artist: 'MONGOL800',
    lowLabel: 'mid1A#',
    highLabel: 'mid2G#',
    gender: 'male',
  },

  {
    title: '宿命',
    artist: 'Official髭男dism',
    lowLabel: 'mid1E',
    highLabel: 'hiC',
    gender: 'hard',
  },
  {
    title: 'モンストロ',
    artist: 'Ado',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'SOS',
    artist: 'tuki.',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: 'Truth in the dark',
    artist: 'LANA',
    lowLabel: 'mid1E',
    highLabel: 'hiF#',
    gender: 'hard',
  },
  {
    title: '777',
    artist: 'YAO',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'Live to Survive',
    artist: 'Aimer',
    lowLabel: 'mid2B',
    highLabel: 'hiC',
    gender: 'female',
  },
  {
    title: 'Love me forever!',
    artist: 'Ado',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'うるさ',
    artist: 'Ayase',
    lowLabel: 'lowG',
    highLabel: 'mid2D#',
    gender: 'male',
  },
  {
    title: '景色',
    artist: 'JI BLUE, JO1 & INI',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: '新宝島',
    artist: 'サカナクション',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
  },

  {
    title: '翼の折れたエンジェル',
    artist: 'LANA',
    lowLabel: 'mid2B',
    highLabel: 'hiC#',
    gender: 'female',
  },
  {
    title: 'Standing Here',
    artist: 'BMSG STRIKERS',
    lowLabel: 'lowF',
    highLabel: 'hiE',
    gender: 'male',
  },
  {
    title: 'My Affection',
    artist: 'Kis-My-Ft2',
    lowLabel: 'mid1C',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: '春に舞う',
    artist: 'Ado',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'Dance Forever',
    artist: 'SixTONES',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'male',
  },
  {
    title: 'お姫様の作り方',
    artist: '=LOVE',
    lowLabel: 'mid1G#',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: 'スターダスト',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiD#',
    gender: 'hard',
  },
  {
    title: 'きゃわぽっぴんどぅー',
    artist: 'iLiFE!',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: '絶対アイドル辞めないで',
    artist: '=LOVE',
    lowLabel: 'mid1G#',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'Fiction Love',
    artist: '中島健人',
    lowLabel: 'mid1C',
    highLabel: 'hiC',
    gender: 'male',
  },

  {
    title: 'SUMMER SONG',
    artist: 'YUI',
    lowLabel: 'mid1G',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'YES',
    artist: 'LiSA',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: '灰色',
    artist: '大森元貴',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'あぶく',
    artist: 'ヨルシカ',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: '綺羅',
    artist: 'Ado',
    lowLabel: 'mid2B',
    highLabel: 'hiC#',
    gender: 'female',
  },
  {
    title: 'ルミナス - Luminous',
    artist: 'アイナ・ジ・エンド',
    lowLabel: 'mid1D#',
    highLabel: 'hiD#',
    gender: 'hard',
  },
  {
    title: 'らしさ',
    artist: 'Official髭男dism',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'both',
  },
  {
    title: 'ノーダウト',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'hard',
  },
  {
    title: '章',
    artist: '緑黄色社会',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'エルダーフラワー',
    artist: 'Official髭男dism',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },

  {
    title: 'GOOD DAY',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'hard',
  },
  {
    title: 'コールドスリープ',
    artist: 'Perfume',
    lowLabel: 'mid2C',
    highLabel: 'hiG',
    gender: 'female',
  },
  {
    title: 'Sanitizer',
    artist: 'Official髭男dism',
    lowLabel: 'mid1C#',
    highLabel: 'hiE',
    gender: 'hard',
  },
  {
    title: '劇上',
    artist: 'YOASOBI',
    lowLabel: 'mid1G',
    highLabel: 'hiF#',
    gender: 'female',
  },
  {
    title: 'アイドルライフメガパック',
    artist: 'iLiFE!',
    lowLabel: 'mid2A#',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: '風のアンセム (feat. suis from ヨルシカ)',
    artist: 'Eve',
    lowLabel: 'mid1A',
    highLabel: 'hiD#',
    gender: 'hard',
  },
  {
    title: 'Hallelujah',
    artist: '[Alexandros]',
    lowLabel: 'mid1C',
    highLabel: 'hiD#',
    gender: 'male',
  },
  {
    title: '怪獣の花唄',
    artist: 'Vaundy',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'male',
  },
  {
    
      title: 'Lemon',
      artist: '米津玄師',
      lowLabel: 'mid1B',
      highLabel: 'hiB',
      gender: 'male',
    
  },
  {
    title: 'マリーゴールド',
    artist: 'あいみょん',
    lowLabel: 'mid1F',
    highLabel: 'hiB',
    gender: 'female',
  },
  {
    title: '残酷な天使のテーゼ',
    artist: '高橋洋子',
    lowLabel: 'mid2A',
    highLabel: 'hiC',
    gender: 'female',
  },
  {
    title: 'サウダージ',
    artist: 'ポルノグラフィティ',
    lowLabel: 'mid1G',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: '高嶺の花子さん',
    artist: 'back number',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'さよならエレジー',
    artist: '菅田将暉',
    lowLabel: 'mid1C#',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: '奏（かなで）',
    artist: 'スキマスイッチ',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'ひまわりの約束',
    artist: '秦 基博',
    lowLabel: 'mid1F',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'カブトムシ',
    artist: 'aiko',
    lowLabel: 'mid1G#',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'チェリー',
    artist: 'スピッツ',
    lowLabel: 'mid1E',
    highLabel: 'hiA',
    gender: 'male',
  },
  {
    title: '恋人ごっこ',
    artist: 'マカロニえんぴつ',
    lowLabel: 'mid1F#',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: '天体観測',
    artist: 'BUMP OF CHICKEN',
    lowLabel: 'mid1C',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: '真夏の果実',
    artist: 'サザンオールスターズ',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'HOT LIMIT',
    artist: 'T.M.Revolution',
    lowLabel: 'mid1F#',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: '打上花火',
    artist: 'DAOKO×米津玄師',
    lowLabel: 'mid1A#',
    highLabel: 'hiD#',
    gender: 'both',
  },
  {
    title: '点描の唄 (feat. 井上苑子)',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'both',
  },
  {
    title: 'ベテルギウス',
    artist: '優里',
    lowLabel: 'lowF#',
    highLabel: 'hiD',
    gender: 'male',
  },
  {
    title: 'シンデレラボーイ',
    artist: 'Saucy Dog',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'ハナミズキ',
    artist: '一青窈',
    lowLabel: 'mid1G',
    highLabel: 'hiC#',
    gender: 'female',
  },
  {
    title: 'First Love',
    artist: '宇多田ヒカル',
    lowLabel: 'mid1E',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: '愛をこめて花束を',
    artist: 'Superfly',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'Wherever you are',
    artist: 'ONE OK ROCK',
    lowLabel: 'lowF',
    highLabel: 'hiC',
    gender: 'hard',
  },
  {
    title: '丸の内サディスティック',
    artist: '椎名林檎',
    lowLabel: 'mid2A#',
    highLabel: 'hiG',
    gender: 'female',
  },
  {
    title: '裸の心',
    artist: 'あいみょん',
    lowLabel: 'mid1F',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'Mela!',
    artist: '緑黄色社会',
    lowLabel: 'mid1G#',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'ただ君に晴れ',
    artist: 'ヨルシカ',
    lowLabel: 'mid2D',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'アイドル',
    artist: 'YOASOBI',
    lowLabel: 'mid1F#',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: '勇者',
    artist: 'YOASOBI',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'SPECIALZ',
    artist: 'King Gnu',
    lowLabel: 'mid1C#',
    highLabel: 'mid2F#',
    gender: 'male',
  },
  {
    title: '絆ノ奇跡',
    artist: 'MAN WITH A MISSION & milet',
    lowLabel: 'mid1F',
    highLabel: 'hiC',
    gender: 'female',
  },
  {
    title: 'こっから',
    artist: 'SixTONES',
    lowLabel: 'mid1E',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: '青のすみか',
    artist: 'キタニタツヤ',
    lowLabel: 'mid1A#',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'ラビットホール',
    artist: 'DECO*27',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'both',
  },
  {
    title: '強風オールバック',
    artist: 'ゆこぴ',
    lowLabel: 'mid1G',
    highLabel: 'hiA',
    gender: 'both',
  },
  {
    title: 'オーバーライド',
    artist: '吉田夜世',
    lowLabel: 'mid1G#',
    highLabel: 'hiC#',
    gender: 'female',
  },
  {
    title: '晩餐歌',
    artist: 'tuki.',
    lowLabel: 'mid1G',
    highLabel: 'hiF#',
    gender: 'female',
  },
  {
    title: '美少女無罪♡パイレーツ',
    artist: '宝鐘マリン',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'INTERNET YAMERO',
    artist: 'NEEDY GIRL OVERDOSE, KOTOKO & Aiobahn',
    lowLabel: 'mid1F',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: '君のまま',
    artist: '百足 & 韻マン',
    lowLabel: 'lowF#',
    highLabel: 'mid2E',
    gender: 'male',
  },
  {
    title: 'バグ (feat. 宵崎奏, 朝比奈まふゆ, 東雲絵名, 暁山瑞希 & 鏡音レン)',
    artist: '25時、ナイトコードで。',
    lowLabel: 'mid2A#',
    highLabel: 'hiF#',
    gender: 'female',
  },
  {
    title: 'あいしていたのに',
    artist: 'MARETU',
    lowLabel: 'mid2C#',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: 'LADY',
    artist: '米津玄師',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: '匿名M',
    artist: 'ピノキオピー',
    lowLabel: 'lowF#',
    highLabel: 'hiC#',
    gender: 'hard',
  },
  {
    title: 'Mainstream',
    artist: 'BE:FIRST',
    lowLabel: 'lowF',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'ホワイトノイズ',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiD#',
    gender: 'hard',
  },
  {
    title: 'fake face dance music',
    artist: '音田雅則',
    lowLabel: 'lowG#',
    highLabel: 'mid2F#',
    gender: 'male',
  },
  {
    title: 'ダーリン',
    artist: '須田景凪',
    lowLabel: 'mid1F',
    highLabel: 'hiC#',
    gender: 'both',
  },
  {
    title: 'スピカ',
    artist: 'ロクデナシ',
    lowLabel: 'mid1F#',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'TATTOO',
    artist: 'Official髭男dism',
    lowLabel: 'mid1C',
    highLabel: 'hiC',
    gender: 'hard',
  },
  {
    title: 'アタシは問題作',
    artist: 'Ado',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'hard',
  },
  {
    title: 'フライデー・ナイト',
    artist: 'なとり',
    lowLabel: 'lowG#',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: 'ランデヴー',
    artist: 'シャイトープ',
    lowLabel: 'mid1C',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: '紡ぐ',
    artist: 'とた',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'レクイエム (feat. 星街すいせい)',
    artist: 'Kanaria',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'セブンティーン',
    artist: 'YOASOBI',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
  },
  {
    title: 'そんなbitterな話',
    artist: 'Vaundy',
    lowLabel: 'mid1E',
    highLabel: 'hiE',
    gender: 'male',
  },
  {
    title: '向日葵',
    artist: 'Ado',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'Biri-Biri',
    artist: 'YOASOBI',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: '美しい鰭',
    artist: 'スピッツ',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'クラクラ',
    artist: 'Ado',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'Anytime Anywhere',
    artist: 'milet',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: 'のだ',
    artist: '大漠波新',
    lowLabel: 'mid1G',
    highLabel: 'hiD#',
    gender: 'female',
  },
  {
    title: 'slow...',
    artist: 'Snow Man',
    lowLabel: 'mid1A#',
    highLabel: 'mid2F#',
    gender: 'male',
  },
  {
    title: 'spiral',
    artist: 'LONGMAN',
    lowLabel: 'mid1A#',
    highLabel: 'hiC',
    gender: 'male',
  },
  {
    title: 'ライアーダンサー',
    artist: 'マサラダ',
    lowLabel: 'mid1F#',
    highLabel: 'hiE',
    gender: 'female',
  },
  {
    title: '可愛いあの子が気にゐらない',
    artist: 'なるみや',
    lowLabel: 'mid2C',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: '猿芝居',
    artist: 'なとり',
    lowLabel: 'mid1A',
    highLabel: 'mid2E',
    gender: 'male',
  },
  {
    title: 'コイコガレ',
    artist: 'milet & MAN WITH A MISSION',
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'female',
  },
  {
    title: 'CEREMONY',
    artist: 'Stray Kids',
    lowLabel: 'mid1E',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: 'カリスマックス',
    artist: 'Snow Man',
    lowLabel: 'mid1A#',
    highLabel: 'hiD',
    gender: 'hard',
  },
  {
    title: 'タペストリー',
    artist: 'Snow Man',
    lowLabel: 'mid1F',
    highLabel: 'hiA#',
    gender: 'both',
  },
  {
    title: 'Dangerholic',
    artist: 'Snow Man',
    lowLabel: 'lowF#',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: 'プロポーズ',
    artist: 'なとり',
    lowLabel: 'mid1C',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: '君の彼氏になりたい。',
    artist: 'Snow Man',
    lowLabel: 'mid1C',
    highLabel: 'mid2G',
    gender: 'male',
  },
  {
    title: '革命道中 - On The Way',
    artist: 'アイナ・ジ・エンド',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'hard',
  },
  {
    title: 'テレパシ',
    artist: 'DECO*27',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: 'SBY',
    artist: 'Snow Man',
    lowLabel: 'mid1D#',
    highLabel: 'hiA',
    gender: 'male',
  },
  {
    title: 'BOW AND ARROW',
    artist: '米津玄師',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'Plazma',
    artist: '米津玄師',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'LOVE TRIGGER',
    artist: 'Snow Man',
    lowLabel: 'mid1C#',
    highLabel: 'hiC#',
    gender: 'male',
  },
  {
    title: 'どんなときも。',
    artist: '槇原敬之',
    lowLabel: 'mid1E',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'SAY YES',
    artist: 'CHAGE and ASKA',
    lowLabel: 'mid1D',
    highLabel: 'mid2G#',
    gender: 'male',
  },
  {
    title: 'ラブ・ストーリーは突然に',
    artist: '小田和正',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'hard',
  },
  {
    title: '冬がはじまるよ',
    artist: '槇原敬之',
    lowLabel: 'mid1E',
    highLabel: 'mid2G',
    gender: 'male',
  },
  {
    title: 'Say Anything',
    artist: 'X JAPAN',
    lowLabel: 'mid1F',
    highLabel: 'hiD',
    gender: 'female',
  },
  {
    title: 'あなたに会えてよかった',
    artist: '小泉今日子',
    lowLabel: 'mid2A#',
    highLabel: 'hiB',
    gender: 'female',
  },
  {
    title: 'それが大事',
    artist: '大事MANブラザーズバンド',
    lowLabel: 'mid1E',
    highLabel: 'hiA#',
    gender: 'male',
  },
  {
    title: 'PIECE OF MY WISH',
    artist: '今井美樹',
    lowLabel: 'mid2A',
    highLabel: 'hiC',
    gender: 'female',
  },
  {
    title: '孤独のRunaway',
    artist: 'B\'z',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'male',
  },
  {
    title: 'Eyes to me',
    artist: 'DREAMS COME TRUE',
    lowLabel: 'mid1G#',
    highLabel: 'hiC#',
    gender: 'female',
  },
  {
    title: '少年期',
    artist: '武田鉄矢',
    lowLabel: 'mid1B',
    highLabel: 'mid2F',
    gender: 'male',
  },
  {
    title: '風の谷のナウシカ',
    artist: '安田成美',
    lowLabel: 'mid1G#',
    highLabel: 'hiB',
    gender: 'female',
  },
  {
    title: 'LOVE TRAIN',
    artist: 'TMN',
    lowLabel: 'mid1C',
    highLabel: 'mid2F#',
    gender: 'male',
  },
  {
    title: 'Wild Life',
    artist: 'B\'z',
    lowLabel: 'mid1G#',
    highLabel: 'hiB',
    gender: 'female',
  },
]

export const SONGS =
  RAW_SONGS.map(
    (song, index) => {

      const minMidi =
        pitchLabelToMidi(
          song.lowLabel
        )

      const maxMidi =
        pitchLabelToMidi(
          song.highLabel
        )

      return {
        id:
          song.id ??
          index + 1,

        ...song,

        minMidi,
        maxMidi,

        lowMidi:
          minMidi,

        highMidi:
          maxMidi,

        low:
          minMidi,

        high:
          maxMidi,

        sourceType:
          '音域ベースの目安',
      }
    }
  )