// キミキー 楽曲データ 100曲版
// ※音域は「音域ベースの目安」です。
// 音源・歌唱方法・裏声を含むかなどによって実際の音域は異なる場合があります。

const NOTE_INDEX = {
  C: 0,
  'C#': 1,
  D: 2,
  'D#': 3,
  E: 4,
  F: 5,
  'F#': 6,
  G: 7,
  'G#': 8,
  A: 9,
  'A#': 10,
  B: 11,
}

function pitchLabelToMidi(label) {
  const match =
    label.match(
      /^(low|mid1|mid2|hi)([A-G](?:#)?)$/
    )

  if (!match) {
    throw new Error(
      `Unknown pitch label: ${label}`
    )
  }

  const [, band, note] = match

  const bandStartMidi = {
    low: 33,  // A1
    mid1: 45, // A2
    mid2: 57, // A3
    hi: 69,   // A4
  }

  const offsetFromA = {
    A: 0,
    'A#': 1,
    B: 2,
    C: 3,
    'C#': 4,
    D: 5,
    'D#': 6,
    E: 7,
    F: 8,
    'F#': 9,
    G: 10,
    'G#': 11,
  }

  return (
    bandStartMidi[band] +
    offsetFromA[note]
  )
}

const RAW_SONGS = [
  {
    title: 'Brand New',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiE',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ライラック',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1E',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '好きすぎて滅!',
    artist: 'M!LK',
    lowLabel: 'mid1B',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'IRIS OUT',
    artist: '米津玄師',
    lowLabel: 'mid1A#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '青と夏',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D#',
    highLabel: 'hiE',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Blue Jeans',
    artist: 'HANA',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '恋、はじめました。',
    artist: '=LOVE',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Soranji',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C',
    highLabel: 'hiF#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'lulu.',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C#',
    highLabel: 'hiD#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'アイドルパワー',
    artist: 'M!LK',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: 'HAPPY BIRTHDAY',
    artist: 'back number',
    lowLabel: 'lowG#',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ケセラセラ',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiF',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'I Got Your Back',
    artist: 'ILLIT & HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ダーリン',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ROSE',
    artist: 'HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ブルーアンバー',
    artist: 'back number',
    lowLabel: 'mid1A#',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '僕のこと',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiD#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'マイオンリー',
    artist: 'SixTONES',
    lowLabel: 'mid1C#',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '水平線',
    artist: 'back number',
    lowLabel: 'mid1C#',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ヒロイン',
    artist: 'back number',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: 'Magic',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C#',
    highLabel: 'hiF',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '怪獣',
    artist: 'サカナクション',
    lowLabel: 'mid1F',
    highLabel: 'hiB',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '115万キロのフィルム',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ダンスホール',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid2A',
    highLabel: 'hiF#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Pretender',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'AIZO',
    artist: 'King Gnu',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ブルーアンビエンス (feat. asmi)',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'BAD',
    artist: 'ATEEZ',
    lowLabel: 'mid1F#',
    highLabel: 'hiC',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'BPM (feat. KREVA)',
    artist: 'Kvi Baba',
    lowLabel: 'mid1D',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Automatic',
    artist: '宇多田ヒカル',
    lowLabel: 'mid1F#',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: 'インディゴ地平線',
    artist: 'スピッツ',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Subtitle',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'StaRt',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1F#',
    highLabel: 'hiB',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Bad Girl',
    artist: 'HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '波乗りジョニー',
    artist: '桑田佳祐',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'インフェルノ',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1B',
    highLabel: 'hiD#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '夜に駆ける',
    artist: 'YOASOBI',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'きらり',
    artist: '藤井風',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '劇薬中毒',
    artist: '=LOVE',
    lowLabel: 'mid2A',
    highLabel: 'hiC#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'SAD SONG',
    artist: 'ちゃんみな',
    lowLabel: 'mid1F',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },

  {
    title: 'ドライフラワー',
    artist: '優里',
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'Never Grow Up',
    artist: 'ちゃんみな',
    lowLabel: 'mid1F',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'ハレンチ',
    artist: 'ちゃんみな',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'クスシキ',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1E',
    highLabel: 'hiF',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Love so sweet',
    artist: '嵐',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '群青',
    artist: 'YOASOBI',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Tiger',
    artist: 'HANA',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'イエスタデイ',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '今夜このまま',
    artist: 'あいみょん',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'JANE DOE',
    artist: '米津玄師 & 宇多田ヒカル',
    lowLabel: 'mid1C',
    highLabel: 'hiD#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: 'NON STOP',
    artist: 'HANA',
    lowLabel: 'mid1F#',
    highLabel: 'hiA#',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ロマンチシズム',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1C',
    highLabel: 'hiD#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '怪盗',
    artist: 'back number',
    lowLabel: 'mid1C#',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Golden',
    artist: 'HUNTR/X',
    lowLabel: 'mid1D',
    highLabel: 'hiF#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'KISS N TELL',
    artist: 'aespa',
    lowLabel: 'mid1G#',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '晴々',
    artist: '緑黄色社会',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Blue Shining Star',
    artist: 'アイナ・ジ・エンド',
    lowLabel: 'mid1B',
    highLabel: 'hiE',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'グッタイム',
    artist: 'Snow Man',
    lowLabel: 'mid1F',
    highLabel: 'hiC',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'イケナイ太陽',
    artist: 'ORANGE RANGE',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '小さな恋のうた',
    artist: 'MONGOL800',
    lowLabel: 'mid1A#',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: '宿命',
    artist: 'Official髭男dism',
    lowLabel: 'mid1E',
    highLabel: 'hiC',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'モンストロ',
    artist: 'Ado',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'SOS',
    artist: 'tuki.',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Truth in the dark',
    artist: 'LANA',
    lowLabel: 'mid1E',
    highLabel: 'hiF#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '777',
    artist: 'YAO',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Live to Survive',
    artist: 'Aimer',
    lowLabel: 'mid2B',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'Love me forever!',
    artist: 'Ado',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'うるさ',
    artist: 'Ayase',
    lowLabel: 'lowG',
    highLabel: 'mid2D#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '景色',
    artist: 'JI BLUE, JO1 & INI',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '新宝島',
    artist: 'サカナクション',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: '翼の折れたエンジェル',
    artist: 'LANA',
    lowLabel: 'mid2B',
    highLabel: 'hiC#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Standing Here',
    artist: 'BMSG STRIKERS',
    lowLabel: 'lowF',
    highLabel: 'hiE',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'My Affection',
    artist: 'Kis-My-Ft2',
    lowLabel: 'mid1C',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '春に舞う',
    artist: 'Ado',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'Dance Forever',
    artist: 'SixTONES',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'お姫様の作り方',
    artist: '=LOVE',
    lowLabel: 'mid1G#',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'スターダスト',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiD#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'きゃわぽっぴんどぅー',
    artist: 'iLiFE!',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '絶対アイドル辞めないで',
    artist: '=LOVE',
    lowLabel: 'mid1G#',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Fiction Love',
    artist: '中島健人',
    lowLabel: 'mid1C',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },

  {
    title: 'SUMMER SONG',
    artist: 'YUI',
    lowLabel: 'mid1G',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'YES',
    artist: 'LiSA',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: '灰色',
    artist: '大森元貴',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'あぶく',
    artist: 'ヨルシカ',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '綺羅',
    artist: 'Ado',
    lowLabel: 'mid2B',
    highLabel: 'hiC#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'ルミナス - Luminous',
    artist: 'アイナ・ジ・エンド',
    lowLabel: 'mid1D#',
    highLabel: 'hiD#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'らしさ',
    artist: 'Official髭男dism',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ノーダウト',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '章',
    artist: '緑黄色社会',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'エルダーフラワー',
    artist: 'Official髭男dism',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    title: 'GOOD DAY',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'コールドスリープ',
    artist: 'Perfume',
    lowLabel: 'mid2C',
    highLabel: 'hiG',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Sanitizer',
    artist: 'Official髭男dism',
    lowLabel: 'mid1C#',
    highLabel: 'hiE',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '劇上',
    artist: 'YOASOBI',
    lowLabel: 'mid1G',
    highLabel: 'hiF#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'アイドルライフメガパック',
    artist: 'iLiFE!',
    lowLabel: 'mid2A#',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '風のアンセム (feat. suis from ヨルシカ)',
    artist: 'Eve',
    lowLabel: 'lowF#',
    highLabel: 'hiD#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Hallelujah',
    artist: '[Alexandros]',
    lowLabel: 'mid1C',
    highLabel: 'hiD#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '怪獣の花唄',
    artist: 'Vaundy',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    
      title: 'Lemon',
      artist: '米津玄師',
      lowLabel: 'mid1B',
      highLabel: 'hiB',
      gender: 'male',
      singerGender: 'male',
      difficulty: 'unknown',
    
  },
  {
    title: 'マリーゴールド',
    artist: 'あいみょん',
    lowLabel: 'mid1F',
    highLabel: 'hiB',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: '残酷な天使のテーゼ',
    artist: '高橋洋子',
    lowLabel: 'mid2A',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'サウダージ',
    artist: 'ポルノグラフィティ',
    lowLabel: 'mid1G',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '高嶺の花子さん',
    artist: 'back number',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'さよならエレジー',
    artist: '菅田将暉',
    lowLabel: 'mid1C#',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '奏（かなで）',
    artist: 'スキマスイッチ',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ひまわりの約束',
    artist: '秦 基博',
    lowLabel: 'mid1F',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'カブトムシ',
    artist: 'aiko',
    lowLabel: 'mid1G#',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'チェリー',
    artist: 'スピッツ',
    lowLabel: 'mid1E',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '恋人ごっこ',
    artist: 'マカロニえんぴつ',
    lowLabel: 'mid1F#',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '天体観測',
    artist: 'BUMP OF CHICKEN',
    lowLabel: 'mid1C',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '真夏の果実',
    artist: 'サザンオールスターズ',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'HOT LIMIT',
    artist: 'T.M.Revolution',
    lowLabel: 'mid1F#',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '打上花火',
    artist: 'DAOKO×米津玄師',
    lowLabel: 'mid1A#',
    highLabel: 'hiD#',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '点描の唄 (feat. 井上苑子)',
    artist: 'Mrs. GREEN APPLE',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ベテルギウス',
    artist: '優里',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'シンデレラボーイ',
    artist: 'Saucy Dog',
    lowLabel: 'mid1D#',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ハナミズキ',
    artist: '一青窈',
    lowLabel: 'mid1G',
    highLabel: 'hiC#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'First Love',
    artist: '宇多田ヒカル',
    lowLabel: 'mid1E',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '愛をこめて花束を',
    artist: 'Superfly',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Wherever you are',
    artist: 'ONE OK ROCK',
    lowLabel: 'mid1G#',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '丸の内サディスティック',
    artist: '椎名林檎',
    lowLabel: 'mid2A#',
    highLabel: 'hiG',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: '裸の心',
    artist: 'あいみょん',
    lowLabel: 'mid1F',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'Mela!',
    artist: '緑黄色社会',
    lowLabel: 'mid1G#',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ただ君に晴れ',
    artist: 'ヨルシカ',
    lowLabel: 'mid2D',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'アイドル',
    artist: 'YOASOBI',
    lowLabel: 'mid1F#',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '勇者',
    artist: 'YOASOBI',
    lowLabel: 'mid1G',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'SPECIALZ',
    artist: 'King Gnu',
    lowLabel: 'mid1C#',
    highLabel: 'mid2F#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '絆ノ奇跡',
    artist: 'MAN WITH A MISSION & milet',
    lowLabel: 'mid1F',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'こっから',
    artist: 'SixTONES',
    lowLabel: 'mid1E',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '青のすみか',
    artist: 'キタニタツヤ',
    lowLabel: 'mid1A#',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'ラビットホール',
    artist: 'DECO*27',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '強風オールバック',
    artist: 'ゆこぴ',
    lowLabel: 'mid1G',
    highLabel: 'hiA',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'オーバーライド',
    artist: '吉田夜世',
    lowLabel: 'mid1G#',
    highLabel: 'hiC#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '晩餐歌',
    artist: 'tuki.',
    lowLabel: 'mid1G',
    highLabel: 'hiF#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '美少女無罪♡パイレーツ',
    artist: '宝鐘マリン',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'INTERNET YAMERO',
    artist: 'NEEDY GIRL OVERDOSE, KOTOKO & Aiobahn',
    lowLabel: 'mid1F',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '君のまま',
    artist: '百足 & 韻マン',
    lowLabel: 'lowF#',
    highLabel: 'mid2E',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'バグ (feat. 宵崎奏, 朝比奈まふゆ, 東雲絵名, 暁山瑞希 & 鏡音レン)',
    artist: '25時、ナイトコードで。',
    lowLabel: 'mid2A#',
    highLabel: 'hiF#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'あいしていたのに',
    artist: 'MARETU',
    lowLabel: 'mid2C#',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'LADY',
    artist: '米津玄師',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '匿名M',
    artist: 'ピノキオピー',
    lowLabel: 'lowF#',
    highLabel: 'hiC#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Mainstream',
    artist: 'BE:FIRST',
    lowLabel: 'lowF',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ホワイトノイズ',
    artist: 'Official髭男dism',
    lowLabel: 'mid1D#',
    highLabel: 'hiD#',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'fake face dance music',
    artist: '音田雅則',
    lowLabel: 'lowG#',
    highLabel: 'mid2F#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'ダーリン',
    artist: '須田景凪',
    lowLabel: 'mid1F',
    highLabel: 'hiC#',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'スピカ',
    artist: 'ロクデナシ',
    lowLabel: 'mid1F#',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'TATTOO',
    artist: 'Official髭男dism',
    lowLabel: 'mid1C',
    highLabel: 'hiC',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'アタシは問題作',
    artist: 'Ado',
    lowLabel: 'mid1D',
    highLabel: 'hiD',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'フライデー・ナイト',
    artist: 'なとり',
    lowLabel: 'lowG#',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'ランデヴー',
    artist: 'シャイトープ',
    lowLabel: 'mid1C',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '紡ぐ',
    artist: 'とた',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'レクイエム (feat. 星街すいせい)',
    artist: 'Kanaria',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'セブンティーン',
    artist: 'YOASOBI',
    lowLabel: 'mid1F',
    highLabel: 'hiF',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'そんなbitterな話',
    artist: 'Vaundy',
    lowLabel: 'mid1E',
    highLabel: 'hiE',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '向日葵',
    artist: 'Ado',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'Biri-Biri',
    artist: 'YOASOBI',
    lowLabel: 'mid1G#',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '美しい鰭',
    artist: 'スピッツ',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'クラクラ',
    artist: 'Ado',
    lowLabel: 'mid2A',
    highLabel: 'hiD#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'Anytime Anywhere',
    artist: 'milet',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'のだ',
    artist: '大漠波新',
    lowLabel: 'mid1D#',
    highLabel: 'hiG',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'slow...',
    artist: 'Snow Man',
    lowLabel: 'mid1A#',
    highLabel: 'mid2F#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'spiral',
    artist: 'LONGMAN',
    lowLabel: 'mid1A#',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ライアーダンサー',
    artist: 'マサラダ',
    lowLabel: 'mid1F#',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '可愛いあの子が気にゐらない',
    artist: 'なるみや',
    lowLabel: 'mid2C',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '猿芝居',
    artist: 'なとり',
    lowLabel: 'mid1A',
    highLabel: 'mid2E',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'コイコガレ',
    artist: 'milet & MAN WITH A MISSION',
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'CEREMONY',
    artist: 'Stray Kids',
    lowLabel: 'mid1E',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'カリスマックス',
    artist: 'Snow Man',
    lowLabel: 'mid1A#',
    highLabel: 'hiD',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'タペストリー',
    artist: 'Snow Man',
    lowLabel: 'mid1F',
    highLabel: 'hiA#',
    gender: 'both',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Dangerholic',
    artist: 'Snow Man',
    lowLabel: 'lowF#',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'プロポーズ',
    artist: 'なとり',
    lowLabel: 'mid1C',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '君の彼氏になりたい。',
    artist: 'Snow Man',
    lowLabel: 'mid1C',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '革命道中 - On The Way',
    artist: 'アイナ・ジ・エンド',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'テレパシ',
    artist: 'DECO*27',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'SBY',
    artist: 'Snow Man',
    lowLabel: 'mid1D#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'BOW AND ARROW',
    artist: '米津玄師',
    lowLabel: 'mid1D',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'Plazma',
    artist: '米津玄師',
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'LOVE TRIGGER',
    artist: 'Snow Man',
    lowLabel: 'mid1C#',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'どんなときも。',
    artist: '槇原敬之',
    lowLabel: 'mid1E',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'SAY YES',
    artist: 'CHAGE and ASKA',
    lowLabel: 'mid1D',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'ラブ・ストーリーは突然に',
    artist: '小田和正',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'hard',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '冬がはじまるよ',
    artist: '槇原敬之',
    lowLabel: 'mid1E',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: 'Say Anything',
    artist: 'X JAPAN',
    lowLabel: 'mid1F',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'あなたに会えてよかった',
    artist: '小泉今日子',
    lowLabel: 'mid2A#',
    highLabel: 'hiB',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'それが大事',
    artist: '大事MANブラザーズバンド',
    lowLabel: 'mid1E',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'PIECE OF MY WISH',
    artist: '今井美樹',
    lowLabel: 'mid2A',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: '孤独のRunaway',
    artist: 'B\'z',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'Eyes to me',
    artist: 'DREAMS COME TRUE',
    lowLabel: 'mid1G#',
    highLabel: 'hiC#',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: '少年期',
    artist: '武田鉄矢',
    lowLabel: 'mid1B',
    highLabel: 'mid2F',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    title: '風の谷のナウシカ',
    artist: '安田成美',
    lowLabel: 'mid1G#',
    highLabel: 'hiB',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    title: 'LOVE TRAIN',
    artist: 'TMN',
    lowLabel: 'mid1C',
    highLabel: 'mid2F#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    title: 'WILD LIFE',
    artist: 'B\'z',
    lowLabel: 'mid1G#',
    highLabel: 'hiB',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 193,
    title: '青い春',
    artist: 'back number',
    lowLabel: 'mid1D',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 194,
    title: '思い出せなくなるその日まで',
    artist: 'back number',
    lowLabel: 'mid1B',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 195,
    title: '恋',
    artist: 'back number',
    lowLabel: 'mid1E',
    highLabel: 'mid2F#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 196,
    title: '繋いだ手から',
    artist: 'back number',
    lowLabel: 'mid1C#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 197,
    title: '日曜日',
    artist: 'back number',
    lowLabel: 'mid1F',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 198,
    title: '花束',
    artist: 'back number',
    lowLabel: 'mid1A',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 199,
    title: 'はなびら',
    artist: 'back number',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
 
  {
    id: 201,
    title: 'fish',
    artist: 'back number',
    lowLabel: 'mid1F',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 202,
    title: 'わたがし',
    artist: 'back number',
    lowLabel: 'mid1E',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 203,
    title: '長い間',
    artist: 'Kiroro',
    lowLabel: 'mid2A#',
    highLabel: 'hiC',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 204,
    title: '未来へ',
    artist: 'Kiroro',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 205,
    title: 'アイランド',
    artist: 'レミオロメン',
    lowLabel: 'mid1C',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 206,
    title: '蒼の世界',
    artist: 'レミオロメン',
    lowLabel: 'mid1A',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 207,
    title: 'アカシア',
    artist: 'レミオロメン',
    lowLabel: 'mid1D#',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 208,
    title: '茜空',
    artist: 'レミオロメン',
    lowLabel: 'mid1F#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 209,
    title: 'ヒカレ',
    artist: 'ゆず',
    lowLabel: 'mid1F',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 210,
    title: '表裏一体',
    artist: 'ゆず',
    lowLabel: 'mid1G',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 211,
    title: '元気を出して',
    artist: '竹内まりや',
    lowLabel: 'mid2A',
    highLabel: 'hiA#',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  
  {
    id: 212,
    title: '愛唄',
    artist: 'GReeeeN',
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 213,
    title: '歩み',
    artist: 'GReeeeN',
    lowLabel: 'mid1G',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 214,
    title: '3月9日',
    artist: 'レミオロメン',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 215,
    title: '粉雪',
    artist: 'レミオロメン',
    lowLabel: 'mid1B',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
 
  {
    id: 217,
    title: 'あなたに',
    artist: 'MONGOL800',
    lowLabel: 'mid1A',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 218,
    title: 'キセキ',
    artist: 'GReeeeN',
    lowLabel: 'mid1G',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 219,
    title: '遥か',
    artist: 'GReeeeN',
    lowLabel: 'mid1G',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 220,
    title: '夏色',
    artist: 'ゆず',
    lowLabel: 'mid1F#',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 221,
    title: '栄光の架橋',
    artist: 'ゆず',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 222,
    title: '蕾',
    artist: 'コブクロ',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 223,
    title: '桜',
    artist: 'コブクロ',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 224,
    title: '道',
    artist: 'EXILE',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 225,
    title: 'Lovers Again',
    artist: 'EXILE',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 226,
    title: 'HANABI',
    artist: 'Mr.Children',
    lowLabel: 'mid1A',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 227,
    title: 'しるし',
    artist: 'Mr.Children',
    lowLabel: 'mid1A',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 228,
    title: '虹',
    artist: '菅田将暉',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 229,
    title: 'まちがいさがし',
    artist: '菅田将暉',
    lowLabel: 'mid1C#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  
  {
    id: 230,
    title: '恋',
    artist: '星野源',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 231,
    title: 'SUN',
    artist: '星野源',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  
  {
    id: 232,
    title: '女々しくて',
    artist: 'ゴールデンボンバー',
    lowLabel: 'mid1C#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 233,
    title: '風吹けば恋',
    artist: 'チャットモンチー',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 234,
    title: 'シャングリラ',
    artist: 'チャットモンチー',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 235,
    title: 'Story',
    artist: 'AI',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  
  {
    id: 236,
    title: '三日月',
    artist: '絢香',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  
  {
    id: 237,
    title: '366日',
    artist: 'HY',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 238,
    title: 'CHE.R.RY',
    artist: 'YUI',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    id: 239,
    title: 'Good-bye days',
    artist: 'YUI',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  
 
  
  {
    id: 241,
    title: '恋するフォーチュンクッキー',
    artist: 'AKB48',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 242,
    title: 'ヘビーローテーション',
    artist: 'AKB48',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 243,
    title: '愛のバクダン',
    artist: "B'z",
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 244,
    title: 'C\'mon',
    artist: "B'z",
    lowLabel: 'mid1D',
    highLabel: 'hiA#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 245,
    title: '消えない虹',
    artist: "B'z",
    lowLabel: 'mid1C#',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 246,
    title: 'TIME',
    artist: "B'z",
    lowLabel: 'mid1G',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 247,
    title: 'HOME',
    artist: "B'z",
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 248,
    title: 'もう一度キスしたかった',
    artist: "B'z",
    lowLabel: 'mid1G',
    highLabel: 'mid2G#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 249,
    title: 'YOU & I',
    artist: "B'z",
    lowLabel: 'mid1F',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 250,
    title: 'ゆるぎないものひとつ',
    artist: "B'z",
    lowLabel: 'mid1F#',
    highLabel: 'hiC#',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 251,
    title: '兵、走る',
    artist: "B'z",
    lowLabel: 'mid2C',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 252,
    title: '衝動',
    artist: "B'z",
    lowLabel: 'mid1G',
    highLabel: 'hiC',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 253,
    title: 'ロビンソン',
    artist: 'スピッツ',
    lowLabel: 'mid1E',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 254,
    title: '空も飛べるはず',
    artist: 'スピッツ',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 255,
    title: '楓',
    artist: 'スピッツ',
    lowLabel: 'mid1C',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 256,
    title: '春の歌',
    artist: 'スピッツ',
    lowLabel: 'mid1D',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 257,
    title: 'スターゲイザー',
    artist: 'スピッツ',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 258,
    title: 'Tomorrow never knows',
    artist: 'Mr.Children',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 259,
    title: '終わりなき旅',
    artist: 'Mr.Children',
    lowLabel: 'mid1C',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 260,
    title: 'Sign',
    artist: 'Mr.Children',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 261,
    title: '抱きしめたい',
    artist: 'Mr.Children',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 262,
    title: '名もなき詩',
    artist: 'Mr.Children',
    lowLabel: 'mid1B',
    highLabel: 'hiB',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 263,
    title: 'TSUNAMI',
    artist: 'サザンオールスターズ',
    lowLabel: 'mid1B',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },

  {
    id: 265,
    title: '希望の轍',
    artist: 'サザンオールスターズ',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 266,
    title: '涙のキッス',
    artist: 'サザンオールスターズ',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 267,
    title: '負けないで',
    artist: 'ZARD',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 268,
    title: '揺れる想い',
    artist: 'ZARD',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 269,
    title: 'マイ フレンド',
    artist: 'ZARD',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 270,
    title: '君に逢いたくなったら…',
    artist: 'ZARD',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 271,
    title: 'Time goes by',
    artist: 'Every Little Thing',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 272,
    title: 'fragile',
    artist: 'Every Little Thing',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 273,
    title: 'Dear My Friend',
    artist: 'Every Little Thing',
    lowLabel: 'mid2A',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 274,
    title: 'LOVE LOVE LOVE',
    artist: 'DREAMS COME TRUE',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 275,
    title: '未来予想図II',
    artist: 'DREAMS COME TRUE',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 276,
    title: '何度でも',
    artist: 'DREAMS COME TRUE',
    lowLabel: 'mid1G',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 277,
    title: 'SEASONS',
    artist: '浜崎あゆみ',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    id: 278,
    title: 'Voyage',
    artist: '浜崎あゆみ',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    id: 279,
    title: 'M',
    artist: '浜崎あゆみ',
    lowLabel: 'mid2A',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  
  {
    id: 280,
    title: '雪の華',
    artist: '中島美嘉',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    id: 281,
    title: 'ORION',
    artist: '中島美嘉',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  {
    id: 282,
    title: 'GLAMOROUS SKY',
    artist: 'NANA starring MIKA NAKASHIMA',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 283,
    title: 'secret base ～君がくれたもの～',
    artist: 'ZONE',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 284,
    title: 'Butterfly',
    artist: '木村カエラ',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'female',
    difficulty: 'unknown',
  },
  
  {
    id: 285,
    title: 'そばかす',
    artist: 'JUDY AND MARY',
    lowLabel: 'mid2A',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 286,
    title: 'Over Drive',
    artist: 'JUDY AND MARY',
    lowLabel: 'mid2A',
    highLabel: 'hiE',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 287,
    title: '夏祭り',
    artist: 'Whiteberry',
    lowLabel: 'mid2A',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 288,
    title: '明日への扉',
    artist: 'I WiSH',
    lowLabel: 'mid1G',
    highLabel: 'hiD',
    gender: 'female',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 289,
    title: '世界に一つだけの花',
    artist: 'SMAP',
    lowLabel: 'mid1C',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 290,
    title: '夜空ノムコウ',
    artist: 'SMAP',
    lowLabel: 'mid1C',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 291,
    title: 'One Love',
    artist: '嵐',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  {
    id: 292,
    title: 'Happiness',
    artist: '嵐',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  
  {
    id: 293,
    title: '愛は勝つ',
    artist: 'KAN',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
 
  {
    id: 295,
    title: 'もう恋なんてしない',
    artist: '槇原敬之',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  
  {
    id: 296,
    title: '瞳をとじて',
    artist: '平井堅',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 297,
    title: 'POP STAR',
    artist: '平井堅',
    lowLabel: 'mid1D',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  
  {
    id: 298,
    title: '桜坂',
    artist: '福山雅治',
    lowLabel: 'lowG',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 299,
    title: '家族になろうよ',
    artist: '福山雅治',
    lowLabel: 'lowG',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  
  {
    id: 300,
    title: '少年時代',
    artist: '井上陽水',
    lowLabel: 'mid1C',
    highLabel: 'mid2G',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 301,
    title: 'I LOVE YOU',
    artist: '尾崎豊',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 302,
    title: '卒業',
    artist: '尾崎豊',
    lowLabel: 'mid1B',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'male',
    difficulty: 'unknown',
  },
  {
    id: 303,
    title: '言葉にできない',
    artist: 'オフコース',
    lowLabel: 'mid1C',
    highLabel: 'hiA',
    gender: 'male',
    singerGender: 'unknown',
    difficulty: 'unknown',
  },
  { id: 304, title: '月を見ていた', artist: '米津玄師', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 305, title: 'アドベンチャー', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 306, title: '唱', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 307, title: 'DIGNITY', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 308, title: 'いばら', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 309, title: 'オールナイトレディオ', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 310, title: 'ビリミリオン', artist: '優里', lowLabel: 'lowG', highLabel: 'hiC', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 311, title: '恋人じゃなくなった日', artist: '優里', lowLabel: 'lowG', highLabel: 'hiC', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 312, title: 'Chessboard', artist: 'Official髭男dism', lowLabel: 'mid1C#', highLabel: 'hiC', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 313, title: 'SOULSOUP', artist: 'Official髭男dism', lowLabel: 'mid1D', highLabel: 'hiC#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 314, title: '日常', artist: 'Official髭男dism', lowLabel: 'mid1D', highLabel: 'hiC', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 315, title: 'リンジュー・ラヴ', artist: 'マカロニえんぴつ', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 316, title: '愛の波', artist: 'マカロニえんぴつ', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 317, title: '悲しみはバスに乗って', artist: 'マカロニえんぴつ', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 318, title: '愛の花', artist: 'あいみょん', lowLabel: 'mid1E', highLabel: 'hiC', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 319, title: 'あのね', artist: 'あいみょん', lowLabel: 'mid1E', highLabel: 'hiC#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 320, title: '花', artist: '藤井風', lowLabel: 'mid1B', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 321, title: 'Workin\' Hard', artist: '藤井風', lowLabel: 'mid1B', highLabel: 'hiA#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 322, title: 'トドメの一撃 feat. Cory Wong', artist: 'Vaundy', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 323, title: '現在を生きるのだ。', artist: 'Saucy Dog', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 324, title: '夢みるスーパーマン', artist: 'Saucy Dog', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 325, title: 'オトナブルー', artist: '新しい学校のリーダーズ', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 326, title: 'Suki Lie', artist: '新しい学校のリーダーズ', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 327, title: 'トウキョウ・シャンディ・ランデヴ', artist: 'MAISONdes', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 328, title: 'メフィスト', artist: '女王蜂', lowLabel: 'mid1D', highLabel: 'hiF', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 329, title: '硝子窓', artist: 'King Gnu', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 330, title: 'more than words', artist: '羊文学', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 331, title: '永遠のブルー', artist: '羊文学', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 332, title: 'NIGHT DANCER', artist: 'imase', lowLabel: 'lowG#', highLabel: 'mid2G#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 333, title: 'Nagisa', artist: 'imase', lowLabel: 'lowG#', highLabel: 'mid2G#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 334, title: 'ユートピア', artist: 'imase', lowLabel: 'lowG#', highLabel: 'mid2G#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 335, title: 'I AM', artist: 'IVE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 336, title: 'UNFORGIVEN', artist: 'LE SSERAFIM', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 337, title: 'Perfect Night', artist: 'LE SSERAFIM', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 338, title: 'Super Shy', artist: 'NewJeans', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 339, title: 'ETA', artist: 'NewJeans', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 340, title: 'SET ME FREE', artist: 'TWICE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 341, title: 'Hare Hare', artist: 'TWICE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 342, title: 'Boom Boom Back', artist: 'BE:FIRST', lowLabel: 'lowG', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 343, title: 'Smile Again', artist: 'BE:FIRST', lowLabel: 'lowG', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 344, title: 'D.U.N.K.', artist: 'SKY-HI', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 345, title: 'ABARERO', artist: 'SixTONES', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 346, title: 'CREAK', artist: 'SixTONES', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 347, title: 'Life goes on', artist: 'King & Prince', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 348, title: 'なにもの', artist: 'King & Prince', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 349, title: 'Paradise', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 350, title: 'HEARTRIS', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 351, title: '愛が灯る', artist: 'ロクデナシ', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 352, title: 'slash', artist: 'yama', lowLabel: 'mid1F#', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 353, title: '偽顔', artist: 'yama', lowLabel: 'mid1F#', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 354, title: 'Super Ball', artist: 'TOMOO', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 355, title: 'Ginger', artist: 'TOMOO', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2023, rangeVerified: false },
  
  { id: 356, title: 'Bling-Bang-Bang-Born', artist: 'Creepy Nuts', lowLabel: 'lowG', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 357, title: '二度寝', artist: 'Creepy Nuts', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 358, title: '幾億光年', artist: 'Omoinotake', lowLabel: 'mid1C#', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 359, title: '蕾', artist: 'Omoinotake', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 360, title: 'タイムパラドックス', artist: 'Vaundy', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 361, title: '満ちてゆく', artist: '藤井風', lowLabel: 'mid1B', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 362, title: 'Feelin\' Go(o)d', artist: '藤井風', lowLabel: 'mid1B', highLabel: 'hiA#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 363, title: '晴る', artist: 'ヨルシカ', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 364, title: '忘れてください', artist: 'ヨルシカ', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 365, title: 'I wonder', artist: 'Da-iCE', lowLabel: 'mid1D', highLabel: 'hiC#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 366, title: 'オレンジ', artist: 'SPYAIR', lowLabel: 'mid1C', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 367, title: 'はいよろこんで', artist: 'こっちのけんと', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 368, title: 'もういいよ', artist: 'こっちのけんと', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 369, title: '最高到達点', artist: 'SEKAI NO OWARI', lowLabel: 'mid1D', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 370, title: '花になって', artist: '緑黄色社会', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 371, title: 'サマータイムシンデレラ', artist: '緑黄色社会', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 372, title: 'ナハトムジーク', artist: 'Mrs. GREEN APPLE', lowLabel: 'mid1C#', highLabel: 'hiD#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 373, title: 'コロンブス', artist: 'Mrs. GREEN APPLE', lowLabel: 'mid1D', highLabel: 'hiD#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 374, title: 'Dear', artist: 'Mrs. GREEN APPLE', lowLabel: 'mid1C#', highLabel: 'hiD#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 375, title: 'familie', artist: 'Mrs. GREEN APPLE', lowLabel: 'mid1D', highLabel: 'hiD', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 376, title: 'ANTENNA', artist: 'Mrs. GREEN APPLE', lowLabel: 'mid1D', highLabel: 'hiD#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2023, rangeVerified: false },
  { id: 377, title: '新しい恋人達に', artist: 'back number', lowLabel: 'mid1C', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 378, title: '冬と春', artist: 'back number', lowLabel: 'mid1C', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 379, title: '夢幻', artist: 'MY FIRST STORY × HYDE', lowLabel: 'mid1C', highLabel: 'hiC', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 380, title: 'ファタール', artist: 'GEMN', lowLabel: 'mid1C', highLabel: 'hiC', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 381, title: 'ビビデバ', artist: '星街すいせい', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 382, title: 'モニタリング', artist: 'DECO*27', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 383, title: 'Magnetic', artist: 'ILLIT', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 384, title: 'Cherish (My Love)', artist: 'ILLIT', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 385, title: 'EASY', artist: 'LE SSERAFIM', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 386, title: 'CRAZY', artist: 'LE SSERAFIM', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 387, title: 'Supernova', artist: 'aespa', lowLabel: 'mid1G#', highLabel: 'hiF', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 388, title: 'Armageddon', artist: 'aespa', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 389, title: 'Whiplash', artist: 'aespa', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 390, title: 'How Sweet', artist: 'NewJeans', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 391, title: 'Bubble Gum', artist: 'NewJeans', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 392, title: 'HEYA', artist: 'IVE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 393, title: 'Accendio', artist: 'IVE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 394, title: 'GOAT', artist: 'Number_i', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 395, title: 'BON', artist: 'Number_i', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 396, title: 'INZM', artist: 'Number_i', lowLabel: 'lowG', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 397, title: 'Masterplan', artist: 'BE:FIRST', lowLabel: 'lowG', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 398, title: 'Sailing', artist: 'BE:FIRST', lowLabel: 'lowG', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 399, title: 'We\'ll go together', artist: 'Snow Man', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 400, title: 'BREAKOUT', artist: 'Snow Man', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 401, title: 'GONG', artist: 'SixTONES', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 402, title: '音色', artist: 'SixTONES', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 403, title: 'moooove!!', artist: 'King & Prince', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 404, title: 'halfmoon', artist: 'King & Prince', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 405, title: 'SWEET NONFICTION', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 406, title: 'Rise Up', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 407, title: '鬼ノ宴', artist: '友成空', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 408, title: '睨めっ娘', artist: '友成空', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 409, title: 'かわいいだけじゃだめですか？', artist: 'CUTIE STREET', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 410, title: 'NEW KAWAII', artist: 'FRUITS ZIPPER', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 411, title: 'かがみ', artist: 'FRUITS ZIPPER', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 412, title: '愛♡スクリ～ム！', artist: 'AiScReam', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 413, title: 'Burning', artist: '羊文学', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 414, title: 'Present', artist: 'TOMOO', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 415, title: '幾億光年 (Acoustic)', artist: 'Omoinotake', lowLabel: 'mid1C#', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 416, title: 'I GOT YOU', artist: 'TWICE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 417, title: 'ビターバカンス', artist: 'Mrs. GREEN APPLE', lowLabel: 'mid1D', highLabel: 'hiD#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 418, title: 'APT.', artist: 'ロゼ & ブルーノ・マーズ', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'both', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  
  { id: 419, title: '倍倍FIGHT!', artist: 'CANDY TUNE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 420, title: 'キス・ミー・パティシエ', artist: 'CANDY TUNE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 421, title: 'イイじゃん', artist: 'M!LK', lowLabel: 'mid1B', highLabel: 'hiC#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 422, title: 'テトリス', artist: '柊マグネタイト', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2024, rangeVerified: false },
  { id: 423, title: 'Almond Chocolate', artist: 'ILLIT', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 424, title: 'Burning Flower', artist: 'HANA', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 425, title: 'Drop', artist: 'HANA', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 426, title: 'ノノガ', artist: 'HANA', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  { id: 427, title: '倍倍FIGHT! - Special ver.', artist: 'CANDY TUNE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2025, rangeVerified: false },
  
  { id: 428, title: '勿忘', artist: 'Awesome City Club', lowLabel: 'mid1F#', highLabel: 'hiC#', gender: 'both', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 429, title: '怪物', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 430, title: '優しい彗星', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 431, title: '三原色', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 432, title: 'もう少しだけ', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 433, title: 'たぶん', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 434, title: 'ハルジオン', artist: 'YOASOBI', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 435, title: 'Pale Blue', artist: '米津玄師', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 436, title: '死神', artist: '米津玄師', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 437, title: 'ゆめうつつ', artist: '米津玄師', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 438, title: '不思議', artist: '星野源', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 439, title: '創造', artist: '星野源', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 440, title: 'Cry Baby', artist: 'Official髭男dism', lowLabel: 'mid1D#', highLabel: 'hiC#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 441, title: 'Universe', artist: 'Official髭男dism', lowLabel: 'mid1D', highLabel: 'hiC', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 442, title: 'アポトーシス', artist: 'Official髭男dism', lowLabel: 'mid1C#', highLabel: 'hiC', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 443, title: 'フィラメント', artist: 'Official髭男dism', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 444, title: '旅路', artist: '藤井風', lowLabel: 'mid1B', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 445, title: '燃えよ', artist: '藤井風', lowLabel: 'mid1B', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 446, title: '花占い', artist: 'Vaundy', lowLabel: 'mid1E', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 447, title: 'しわあわせ', artist: 'Vaundy', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 448, title: '踊り子', artist: 'Vaundy', lowLabel: 'mid1E', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 449, title: 'ギラギラ', artist: 'Ado', lowLabel: 'mid1G#', highLabel: 'hiE', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 450, title: '踊', artist: 'Ado', lowLabel: 'mid1G#', highLabel: 'hiF', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 451, title: '会いたくて', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 452, title: '阿修羅ちゃん', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 453, title: '夜のピエロ', artist: 'Ado', lowLabel: 'mid1F#', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 454, title: 'シャッター', artist: '優里', lowLabel: 'lowG', highLabel: 'hiC', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 455, title: '飛行船', artist: '優里', lowLabel: 'mid1B', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 456, title: 'レオ', artist: '優里', lowLabel: 'lowG', highLabel: 'hiC', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 457, title: '黄色', artist: 'back number', lowLabel: 'mid1C#', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 458, title: 'ハート', artist: 'あいみょん', lowLabel: 'mid1F', highLabel: 'hiC#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 459, title: '愛を知るまでは', artist: 'あいみょん', lowLabel: 'mid1E', highLabel: 'hiC#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 460, title: 'Renegades', artist: 'ONE OK ROCK', lowLabel: 'mid1D', highLabel: 'hiC', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 461, title: 'Broken Heart of Gold', artist: 'ONE OK ROCK', lowLabel: 'mid1D', highLabel: 'hiC', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 462, title: 'Take a picture', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 463, title: 'Poppin\' Shakin\'', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 464, title: 'Chopstick', artist: 'NiziU', lowLabel: 'mid1G', highLabel: 'hiD', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 465, title: 'Secret Touch', artist: 'Snow Man', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 466, title: 'HELLO HELLO', artist: 'Snow Man', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 467, title: 'Grandeur', artist: 'Snow Man', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 468, title: 'マスカラ', artist: 'SixTONES', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 469, title: '僕が僕じゃないみたいだ', artist: 'SixTONES', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 470, title: '恋降る月夜に君想ふ', artist: 'King & Prince', lowLabel: 'mid1D', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 471, title: 'Magic Touch', artist: 'King & Prince', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 472, title: 'Permission to Dance', artist: 'BTS', lowLabel: 'mid1C#', highLabel: 'hiC', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 473, title: 'Film out', artist: 'BTS', lowLabel: 'mid1B', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 474, title: 'The Feels', artist: 'TWICE', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 475, title: 'One Last Kiss', artist: '宇多田ヒカル', lowLabel: 'mid1F#', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  { id: 476, title: 'PINK BLOOD', artist: '宇多田ヒカル', lowLabel: 'mid1F#', highLabel: 'hiD#', gender: 'female', singerGender: 'unknown', difficulty: 'unknown', year: 2021, rangeVerified: false },
  
  { id: 477, title: '残響散歌', artist: 'Aimer', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 478, title: '朝が来る', artist: 'Aimer', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 479, title: 'W / X / Y', artist: 'Tani Yuuki', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 480, title: '愛言葉', artist: 'Tani Yuuki', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 481, title: 'ミックスナッツ', artist: 'Official髭男dism', lowLabel: 'mid1D#', highLabel: 'hiC#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 482, title: 'Anarchy', artist: 'Official髭男dism', lowLabel: 'mid1C#', highLabel: 'hiB', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 483, title: '新時代', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiE', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 484, title: '私は最強', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 485, title: '逆光', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiF', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 486, title: 'ウタカタララバイ', artist: 'Ado', lowLabel: 'mid1G#', highLabel: 'hiF#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 487, title: 'Tot Musica', artist: 'Ado', lowLabel: 'mid1F#', highLabel: 'hiF#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 488, title: '世界のつづき', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 489, title: '風のゆくえ', artist: 'Ado', lowLabel: 'mid1G', highLabel: 'hiD#', gender: 'female', singerGender: 'female', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 490, title: 'なんでもないよ、', artist: 'マカロニえんぴつ', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 491, title: '星が泳ぐ', artist: 'マカロニえんぴつ', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 492, title: 'たましいの居場所', artist: 'マカロニえんぴつ', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 493, title: '一途', artist: 'King Gnu', lowLabel: 'mid1C#', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 494, title: '逆夢', artist: 'King Gnu', lowLabel: 'mid1C#', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 495, title: 'カメレオン', artist: 'King Gnu', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 496, title: 'Stardom', artist: 'King Gnu', lowLabel: 'mid1C', highLabel: 'hiA#', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 497, title: '雨燦々', artist: 'King Gnu', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 498, title: 'Habit', artist: 'SEKAI NO OWARI', lowLabel: 'mid1D', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 499, title: 'Diary', artist: 'SEKAI NO OWARI', lowLabel: 'mid1C', highLabel: 'hiA', gender: 'male', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 500, title: 'CITRUS', artist: 'Da-iCE', lowLabel: 'mid1D', highLabel: 'hiC', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 501, title: 'スターマイン', artist: 'Da-iCE', lowLabel: 'mid1D', highLabel: 'hiC#', gender: 'hard', singerGender: 'unknown', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 502, title: '恋風邪にのせて', artist: 'Vaundy', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 503, title: '裸の勇者', artist: 'Vaundy', lowLabel: 'mid1D', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 504, title: 'mabataki', artist: 'Vaundy', lowLabel: 'mid1E', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
  { id: 505, title: 'CHAINSAW BLOOD', artist: 'Vaundy', lowLabel: 'mid1C#', highLabel: 'hiB', gender: 'male', singerGender: 'male', difficulty: 'unknown', year: 2022, rangeVerified: false },
]

export const SONGS =
  RAW_SONGS.map(
    (song, index) => {

      const minMidi =
        pitchLabelToMidi(
          song.lowLabel
        )

      const maxMidi =
        pitchLabelToMidi(
          song.highLabel
        )

      return {
        id:
          song.id ??
          index + 1,

        ...song,

        minMidi,
        maxMidi,

        lowMidi:
          minMidi,

        highMidi:
          maxMidi,

        low:
          minMidi,

        high:
          maxMidi,

        sourceType:
          '音域ベースの目安',
      }
    }
  )
