// キミキー 追加楽曲データ
// 音域未登録の曲は検索対象には入りますが、
// キー判定・SEO個別ページ生成からは除外されます。

const EXTRA_CATALOG = {
  "Mrs. GREEN APPLE": [
    "インフェルノ",
    "Attitude",
    "僕のこと",
    "青と夏",
    "ダンスホール",
    "Magic",
    "ケセラセラ",
    "Soranji",
    "点描の唄",
    "ロマンチシズム",
    "WanteD! WanteD!",
    "StaRt",
    "春愁",
    "ナハトムジーク",
    "Dear",
  ],

  "back number": [
    "高嶺の花子さん",
    "水平線",
    "花束",
    "ハッピーエンド",
    "クリスマスソング",
    "瞬き",
    "HAPPY BIRTHDAY",
    "ヒロイン",
    "怪盗",
    "アイラブユー",
    "わたがし",
    "オールドファッション",
    "大不正解",
    "日曜日",
    "恋",
  ],

  "米津玄師": [
    "Lemon",
    "KICK BACK",
    "感電",
    "馬と鹿",
    "アイネクライネ",
    "ピースサイン",
    "LOSER",
    "Flamingo",
    "Pale Blue",
    "M八七",
    "地球儀",
    "さよーならまたいつか！",
    "LADY",
    "POP SONG",
    "春雷",
  ],

  "Official髭男dism": [
    "Pretender",
    "I LOVE...",
    "Subtitle",
    "ミックスナッツ",
    "Cry Baby",
    "115万キロのフィルム",
    "宿命",
    "ノーダウト",
    "イエスタデイ",
    "Stand By You",
    "Universe",
    "Chessboard",
    "SOULSOUP",
    "TATTOO",
    "Laughter",
  ],

  "Vaundy": [
    "怪獣の花唄",
    "踊り子",
    "不可幸力",
    "裸の勇者",
    "しわあわせ",
    "花占い",
    "恋風邪にのせて",
    "CHAINSAW BLOOD",
    "瞳惚れ",
    "そんなbitterな話",
    "トドメの一撃",
    "タイムパラドックス",
    "ホムンクルス",
    "napori",
    "東京フラッシュ",
  ],

  "あいみょん": [
    "マリーゴールド",
    "裸の心",
    "君はロックを聴かない",
    "愛を伝えたいだとか",
    "ハルノヒ",
    "今夜このまま",
    "貴方解剖純愛歌〜死ね〜",
    "空の青さを知る人よ",
    "さよならの今日に",
    "愛の花",
    "会いに行くのに",
    "双葉",
    "桜が降る夜は",
    "ハート",
    "初恋が泣いている",
  ],

  "YOASOBI": [
    "夜に駆ける",
    "アイドル",
    "群青",
    "怪物",
    "祝福",
    "勇者",
    "ハルジオン",
    "たぶん",
    "アンコール",
    "三原色",
    "優しい彗星",
    "もう少しだけ",
    "好きだ",
    "セブンティーン",
    "ミスター",
  ],

  "Ado": [
    "うっせぇわ",
    "新時代",
    "唱",
    "私は最強",
    "踊",
    "ギラギラ",
    "阿修羅ちゃん",
    "逆光",
    "Tot Musica",
    "世界のつづき",
    "風のゆくえ",
    "会いたくて",
    "永遠のあくる日",
    "向日葵",
    "クラクラ",
  ],

  "King Gnu": [
    "白日",
    "SPECIALZ",
    "一途",
    "逆夢",
    "飛行艇",
    "Teenager Forever",
    "三文小説",
    "傘",
    "Prayer X",
    "BOY",
    "カメレオン",
    "Stardom",
    "雨燦々",
    "Vinyl",
    "Tokyo Rendez-Vous",
  ],

  "優里": [
    "ドライフラワー",
    "ベテルギウス",
    "シャッター",
    "レオ",
    "かくれんぼ",
    "ピーターパン",
    "ビリミリオン",
    "メリーゴーランド",
    "恋人じゃなくなった日",
    "インフィニティ",
    "桜晴",
    "飛行船",
    "ミズキリ",
    "カーテンコール",
    "おにごっこ",
  ],

  "ヨルシカ": [
    "ただ君に晴れ",
    "花に亡霊",
    "だから僕は音楽を辞めた",
    "言って。",
    "春泥棒",
    "晴る",
    "左右盲",
    "アルジャーノン",
    "月光浴",
    "都落ち",
    "斜陽",
    "パレード",
    "ノーチラス",
    "夜行",
    "雨とカプチーノ",
  ],

  "緑黄色社会": [
    "Mela!",
    "花になって",
    "キャラクター",
    "Shout Baby",
    "サマータイムシンデレラ",
    "陽はまた昇るから",
    "sabotage",
    "ずっとずっとずっと",
    "LITMUS",
    "これからのこと、それからのこと",
    "Party!!",
    "恥ずかしいか青春は",
    "始まりの歌",
    "想い人",
    "夏を生きる",
  ],

  "BUMP OF CHICKEN": [
    "天体観測",
    "ray",
    "アカシア",
    "なないろ",
    "クロノスタシス",
    "Sleep Walking Orchestra",
    "SOUVENIR",
    "Hello,world!",
    "新世界",
    "記念撮影",
    "花の名",
    "カルマ",
    "車輪の唄",
    "才悩人応援歌",
    "sailing day",
  ],

  "ONE OK ROCK": [
    "Wherever you are",
    "The Beginning",
    "完全感覚Dreamer",
    "Wasted Nights",
    "Stand Out Fit In",
    "Renegades",
    "We are",
    "Heartache",
    "Clock Strikes",
    "Mighty Long Fall",
    "Taking Off",
    "Save Yourself",
    "Vandalize",
    "Re:make",
    "キミシダイ列車",
  ],

  "スピッツ": [
    "チェリー",
    "ロビンソン",
    "空も飛べるはず",
    "楓",
    "美しい鰭",
    "優しいあの子",
    "魔法のコトバ",
    "春の歌",
    "涙がキラリ☆",
    "渚",
    "スターゲイザー",
    "みなと",
    "運命の人",
    "正夢",
    "愛のことば",
  ],

  "宇多田ヒカル": [
    "First Love",
    "Automatic",
    "Flavor Of Life",
    "One Last Kiss",
    "Beautiful World",
    "花束を君に",
    "traveling",
    "光",
    "Prisoner Of Love",
    "Can You Keep A Secret?",
    "Addicted To You",
    "COLORS",
    "SAKURAドロップス",
    "Keep Tryin’",
    "あなた",
  ],

  "aiko": [
    "カブトムシ",
    "花火",
    "ボーイフレンド",
    "キラキラ",
    "ストロー",
    "相思相愛",
    "milk",
    "桜の時",
    "えりあし",
    "二人",
    "KissHug",
    "横顔",
    "戻れない明日",
    "もっと",
    "くちびる",
  ],

  "椎名林檎": [
    "丸ノ内サディスティック",
    "本能",
    "ギブス",
    "ここでキスして。",
    "歌舞伎町の女王",
    "長く短い祭",
    "NIPPON",
    "公然の秘密",
    "人生は夢だらけ",
    "ありあまる富",
    "罪と罰",
    "幸福論",
    "正しい街",
    "カーネーション",
    "自由へ道連れ",
  ],

  "サカナクション": [
    "新宝島",
    "アイデンティティ",
    "ミュージック",
    "夜の踊り子",
    "忘れられないの",
    "モス",
    "アルクアラウンド",
    "ネイティブダンサー",
    "ルーキー",
    "多分、風。",
    "グッドバイ",
    "さよならはエモーション",
    "ユリイカ",
    "僕と花",
    "Aoi",
  ],

  "Saucy Dog": [
    "シンデレラボーイ",
    "いつか",
    "結",
    "魔法にかけられて",
    "雀ノ欠伸",
    "あぁ、もう。",
    "ゴーストバスター",
    "優しさに溢れた世界で",
    "現在を生きるのだ。",
    "紫苑",
    "雷に打たれて",
    "Be yourself",
    "夢みるスーパーマン",
    "コンタクトケース",
    "リスポーン",
  ],

  "SEKAI NO OWARI": [
    "RPG",
    "Habit",
    "Dragon Night",
    "スターライトパレード",
    "炎と森のカーニバル",
    "眠り姫",
    "虹色の戦争",
    "サザンカ",
    "Hey Ho",
    "RAIN",
    "SOS",
    "silent",
    "ターコイズ",
    "最高到達点",
    "プレゼント",
  ],

  "Creepy Nuts": [
    "Bling-Bang-Bang-Born",
    "オトノケ",
    "のびしろ",
    "かつて天才だった俺たちへ",
    "堕天",
    "よふかしのうた",
    "合法的トビ方ノススメ",
    "助演男優賞",
    "二度寝",
    "ビリケン",
    "たりないふたり",
    "生業",
    "板の上の魔物",
    "顔役",
    "バレる！",
  ],

  "Da-iCE": [
    "CITRUS",
    "I wonder",
    "スターマイン",
    "DREAMIN’ ON",
    "BACK TO BACK",
    "Kartell",
    "FAKE ME FAKE ME OUT",
    "ダンデライオン",
    "Clap and Clap",
    "Promise",
    "ナイモノネダリ",
    "TAKE IT BACK",
    "Story",
    "TOKI",
    "ハッシュ ハッシュ",
  ],

  "マカロニえんぴつ": [
    "なんでもないよ、",
    "恋人ごっこ",
    "ブルーベリー・ナイツ",
    "洗濯機と君とラヂオ",
    "ヤングアダルト",
    "はしりがき",
    "愛の波",
    "リンジュー・ラヴ",
    "たましいの居場所",
    "星が泳ぐ",
    "レモンパイ",
    "然らば",
    "青春と一瞬",
    "hope",
    "月へ行こう",
  ],

  "ポルノグラフィティ": [
    "アゲハ蝶",
    "サウダージ",
    "メリッサ",
    "ハネウマライダー",
    "ミュージック・アワー",
    "アポロ",
    "ジョバイロ",
    "愛が呼ぶほうへ",
    "シスター",
    "ネオメロドラマティック",
    "ヒトリノ夜",
    "今宵、月が見えずとも",
    "オー！リバル",
    "THE DAY",
    "瞬く星の下で",
  ],

  "Mr.Children": [
    "HANABI",
    "Tomorrow never knows",
    "名もなき詩",
    "Sign",
    "innocent world",
    "抱きしめたい",
    "シーソーゲーム〜勇敢な恋の歌〜",
    "しるし",
    "365日",
    "終わりなき旅",
    "GIFT",
    "youthful days",
    "口笛",
    "CROSS ROAD",
    "箒星",
  ],

  "サザンオールスターズ": [
    "TSUNAMI",
    "真夏の果実",
    "希望の轍",
    "いとしのエリー",
    "LOVE AFFAIR〜秘密のデート〜",
    "涙のキッス",
    "エロティカ・セブン",
    "勝手にシンドバッド",
    "HOTEL PACIFIC",
    "太陽は罪な奴",
    "愛の言霊〜Spiritual Message〜",
    "ミス・ブランニュー・デイ",
    "みんなのうた",
    "東京VICTORY",
    "栄光の男",
  ],

  "GLAY": [
    "HOWEVER",
    "誘惑",
    "BELOVED",
    "Winter, again",
    "SOUL LOVE",
    "グロリアス",
    "口唇",
    "pure soul",
    "春を愛する人",
    "とまどい",
    "Way of Difference",
    "BEAUTIFUL DREAMER",
    "時の雫",
    "逢いたい気持ち",
    "生きてく強さ",
  ],

  "L'Arc-en-Ciel": [
    "HONEY",
    "Driver's High",
    "READY STEADY GO",
    "flower",
    "虹",
    "winter fall",
    "HEAVEN'S DRIVE",
    "STAY AWAY",
    "NEO UNIVERSE",
    "Pieces",
    "snow drop",
    "Blurry Eyes",
    "Link",
    "MY HEART DRAWS A DREAM",
    "DAYBREAK'S BELL",
  ],

  "いきものがかり": [
    "ありがとう",
    "YELL",
    "ブルーバード",
    "SAKURA",
    "じょいふる",
    "気まぐれロマンティック",
    "帰りたくなったよ",
    "笑顔",
    "茜色の約束",
    "風が吹いている",
    "コイスルオトメ",
    "うるわしきひと",
    "ホタルノヒカリ",
    "熱情のスペクトラム",
    "いつだって僕らは",
  ],

  "Perfume": [
    "ポリリズム",
    "チョコレイト・ディスコ",
    "FLASH",
    "レーザービーム",
    "Spring of Life",
    "Spending all my time",
    "Magic of Love",
    "Dream Fighter",
    "ワンルーム・ディスコ",
    "不自然なガール",
    "ねぇ",
    "TOKYO GIRL",
    "If you wanna",
    "Cling Cling",
    "ナナナナナイロ",
  ],

  "Superfly": [
    "愛をこめて花束を",
    "Beautiful",
    "タマシイレボリューション",
    "輝く月のように",
    "やさしい気持ちで",
    "Alright!!",
    "My Best Of My Life",
    "Hi-Five",
    "黒い雫",
    "フレア",
    "99",
    "Fall",
    "愛に抱かれて",
    "Gifts",
    "Wildflower",
  ],

  "LiSA": [
    "紅蓮華",
    "炎",
    "crossing field",
    "Rising Hope",
    "Catch the Moment",
    "ADAMAS",
    "unlasting",
    "シルシ",
    "oath sign",
    "一番の宝物",
    "往け",
    "明け星",
    "HADASHi NO STEP",
    "REALiZE",
    "ブラックボックス",
  ],

  "Aimer": [
    "残響散歌",
    "カタオモイ",
    "蝶々結び",
    "Ref:rain",
    "Brave Shine",
    "茜さす",
    "I beg you",
    "コイワズライ",
    "星屑ビーナス",
    "六等星の夜",
    "SPARK-AGAIN",
    "朝が来る",
    "escalate",
    "Sign",
    "花の唄",
  ],

  "Uru": [
    "プロローグ",
    "あなたがいることで",
    "それを愛と呼ぶなら",
    "心得",
    "アンビバレント",
    "振り子",
    "そばにいるよ",
    "Love Song",
    "ファーストラヴ",
    "奇蹟",
    "remember",
    "フリージア",
    "紙一重",
    "君の幸せを",
    "フィラメント",
  ],
}

const EXTRA_RANGE_DATA = {
  Ado: {
    "うっせぇわ": {
      lowLabel: "mid2A",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/35685",
    },
    "永遠のあくる日": {
      lowLabel: "mid1E",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/74372",
    },
  },

  "米津玄師": {
    "KICK BACK": {
      lowLabel: "lowF",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "感電": {
      lowLabel: "mid1A#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "馬と鹿": {
      lowLabel: "mid1C",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "アイネクライネ": {
      lowLabel: "mid1C#",
      highLabel: "mid2G#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "ピースサイン": {
      lowLabel: "mid1D#",
      highLabel: "mid2G#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "LOSER": {
      lowLabel: "mid1D",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "Flamingo": {
      lowLabel: "mid1A",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "M八七": {
      lowLabel: "mid1C#",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "地球儀": {
      lowLabel: "mid1C",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "さよーならまたいつか！": {
      lowLabel: "mid1D",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "POP SONG": {
      lowLabel: "mid1D",
      highLabel: "mid2G",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
    "春雷": {
      lowLabel: "mid1C",
      highLabel: "mid2G#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/1",
    },
  },

  GLAY: {
    "HOWEVER": {
      lowLabel: "mid1D#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "誘惑": {
      lowLabel: "mid1E",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "BELOVED": {
      lowLabel: "mid1C",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "Winter, again": {
      lowLabel: "mid1C#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "SOUL LOVE": {
      lowLabel: "mid1C",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "グロリアス": {
      lowLabel: "mid1C",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "口唇": {
      lowLabel: "mid1F#",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "pure soul": {
      lowLabel: "mid1D#",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "春を愛する人": {
      lowLabel: "mid1D#",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/33658",
    },
    "Way of Difference": {
      lowLabel: "mid1E",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/97",
    },
    "BEAUTIFUL DREAMER": {
      lowLabel: "mid1D",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/1337",
    },
    "時の雫": {
      lowLabel: "mid1D#",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/74496",
    },
    "逢いたい気持ち": {
      lowLabel: "mid1A",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/1336",
    },
    "生きてく強さ": {
      lowLabel: "mid1D",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/1317",
    },
  },

  Uru: {
    "プロローグ": {
      lowLabel: "mid2C",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "あなたがいることで": {
      lowLabel: "mid1E",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "それを愛と呼ぶなら": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "心得": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "アンビバレント": {
      lowLabel: "mid1G",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "振り子": {
      lowLabel: "mid1F#",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "そばにいるよ": {
      lowLabel: "mid1F",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "Love Song": {
      lowLabel: "mid2A",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "ファーストラヴ": {
      lowLabel: "mid1E",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "奇蹟": {
      lowLabel: "mid1F#",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "remember": {
      lowLabel: "mid1G",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "フリージア": {
      lowLabel: "mid2A",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "紙一重": {
      lowLabel: "mid1E",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "君の幸せを": {
      lowLabel: "mid1F#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
    "フィラメント": {
      lowLabel: "mid1F#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/32",
    },
  },

  Aimer: {
    "カタオモイ": {
      lowLabel: "mid1G#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "蝶々結び": {
      lowLabel: "mid1C",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "Ref:rain": {
      lowLabel: "mid1E",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "Brave Shine": {
      lowLabel: "mid1D#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "茜さす": {
      lowLabel: "mid1F#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "I beg you": {
      lowLabel: "mid2A#",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "コイワズライ": {
      lowLabel: "mid1F",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "星屑ビーナス": {
      lowLabel: "mid1F",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "六等星の夜": {
      lowLabel: "mid1G",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "SPARK-AGAIN": {
      lowLabel: "mid1F#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "escalate": {
      lowLabel: "mid1E",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "Sign": {
      lowLabel: "mid1G",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
    "花の唄": {
      lowLabel: "mid1G",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/34",
    },
  },

  "宇多田ヒカル": {
    "Flavor Of Life": {
      lowLabel: "mid1D#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "Beautiful World": {
      lowLabel: "mid2B",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "花束を君に": {
      lowLabel: "mid1D#",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "traveling": {
      lowLabel: "mid1G",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "光": {
      lowLabel: "mid2A#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "Prisoner Of Love": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "Can You Keep A Secret?": {
      lowLabel: "mid1F#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "Addicted To You": {
      lowLabel: "mid1F",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "COLORS": {
      lowLabel: "mid2A",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "SAKURAドロップス": {
      lowLabel: "mid1F",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "Keep Tryin’": {
      lowLabel: "mid1G",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
    "あなた": {
      lowLabel: "mid2C",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/86",
    },
  },

  "スピッツ": {
    "優しいあの子": {
      lowLabel: "mid1G",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "魔法のコトバ": {
      lowLabel: "mid1F",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "涙がキラリ☆": {
      lowLabel: "mid1F",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "渚": {
      lowLabel: "mid1E",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "みなと": {
      lowLabel: "mid1G#",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "運命の人": {
      lowLabel: "mid1F#",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "正夢": {
      lowLabel: "mid1E",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
    "愛のことば": {
      lowLabel: "mid1D",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/23",
    },
  },

  "ONE OK ROCK": {
    "The Beginning": {
      lowLabel: "mid1E",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "完全感覚Dreamer": {
      lowLabel: "mid2A",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Wasted Nights": {
      lowLabel: "mid1E",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Stand Out Fit In": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "We are": {
      lowLabel: "mid1F",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Heartache": {
      lowLabel: "mid1G#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Clock Strikes": {
      lowLabel: "mid2A",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Mighty Long Fall": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Taking Off": {
      lowLabel: "mid1E",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Save Yourself": {
      lowLabel: "mid1G",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "Re:make": {
      lowLabel: "mid1D",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
    "キミシダイ列車": {
      lowLabel: "mid1G#",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/31",
    },
  },

  "BUMP OF CHICKEN": {
    "ray": {
      lowLabel: "mid1A#",
      highLabel: "mid2G",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "アカシア": {
      lowLabel: "mid1D",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "なないろ": {
      lowLabel: "mid1C#",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "Sleep Walking Orchestra": {
      lowLabel: "lowG#",
      highLabel: "mid2F#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "SOUVENIR": {
      lowLabel: "mid1A",
      highLabel: "mid2F#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "Hello,world!": {
      lowLabel: "mid1C",
      highLabel: "mid2G",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "新世界": {
      lowLabel: "mid1C",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "記念撮影": {
      lowLabel: "mid1E",
      highLabel: "mid2E",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "花の名": {
      lowLabel: "mid1C",
      highLabel: "mid2G#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "カルマ": {
      lowLabel: "mid1C",
      highLabel: "mid2F#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "車輪の唄": {
      lowLabel: "mid1D",
      highLabel: "mid2F#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "才悩人応援歌": {
      lowLabel: "mid1C",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
    "sailing day": {
      lowLabel: "mid1D",
      highLabel: "mid2G#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/44",
    },
  },

  "いきものがかり": {
    "ありがとう": {
      lowLabel: "mid1F",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "YELL": {
      lowLabel: "mid1F",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "ブルーバード": {
      lowLabel: "mid2A",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "SAKURA": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "じょいふる": {
      lowLabel: "mid2D",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "気まぐれロマンティック": {
      lowLabel: "mid2A",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "帰りたくなったよ": {
      lowLabel: "mid1G",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "笑顔": {
      lowLabel: "mid2A",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "茜色の約束": {
      lowLabel: "mid1F",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "風が吹いている": {
      lowLabel: "mid1G",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "コイスルオトメ": {
      lowLabel: "mid2B",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "うるわしきひと": {
      lowLabel: "mid1F#",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "ホタルノヒカリ": {
      lowLabel: "mid2C",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "熱情のスペクトラム": {
      lowLabel: "mid1G",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
    "いつだって僕らは": {
      lowLabel: "mid1G#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/337",
    },
  },

  "L'Arc-en-Ciel": {
    "HONEY": {
      lowLabel: "lowF",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "Driver's High": {
      lowLabel: "mid1E",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "READY STEADY GO": {
      lowLabel: "mid1D",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "flower": {
      lowLabel: "mid1C#",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "虹": {
      lowLabel: "lowF",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "winter fall": {
      lowLabel: "lowG#",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "HEAVEN'S DRIVE": {
      lowLabel: "mid1D",
      highLabel: "hiA",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "STAY AWAY": {
      lowLabel: "mid1C",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "NEO UNIVERSE": {
      lowLabel: "mid1E",
      highLabel: "hiF#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "Pieces": {
      lowLabel: "mid1D#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "snow drop": {
      lowLabel: "mid1C",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "Blurry Eyes": {
      lowLabel: "mid1C",
      highLabel: "hiA#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "Link": {
      lowLabel: "mid1D",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "MY HEART DRAWS A DREAM": {
      lowLabel: "mid1A",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
    "DAYBREAK'S BELL": {
      lowLabel: "mid1B",
      highLabel: "hiB",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/71",
    },
  },

  Perfume: {
    "ポリリズム": {
      lowLabel: "mid1G",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "チョコレイト・ディスコ": {
      lowLabel: "mid2A#",
      highLabel: "hiC",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "FLASH": {
      lowLabel: "mid2A#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "レーザービーム": {
      lowLabel: "mid2C",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "Spring of Life": {
      lowLabel: "mid2A#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "Spending all my time": {
      lowLabel: "mid2B",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "Magic of Love": {
      lowLabel: "mid2A",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "Dream Fighter": {
      lowLabel: "mid2A#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "ワンルーム・ディスコ": {
      lowLabel: "mid2C#",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "不自然なガール": {
      lowLabel: "mid2C#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "ねぇ": {
      lowLabel: "mid2A#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "TOKYO GIRL": {
      lowLabel: "mid2A",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "If you wanna": {
      lowLabel: "mid2E",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "Cling Cling": {
      lowLabel: "mid2B",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
    "ナナナナナイロ": {
      lowLabel: "mid2D",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/93",
    },
  },

  Superfly: {
    "Beautiful": {
      lowLabel: "mid2A#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "タマシイレボリューション": {
      lowLabel: "mid2A",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "輝く月のように": {
      lowLabel: "mid1G",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "やさしい気持ちで": {
      lowLabel: "mid1F",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "Alright!!": {
      lowLabel: "mid2B",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "My Best Of My Life": {
      lowLabel: "mid1F#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "Hi-Five": {
      lowLabel: "mid2A#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "黒い雫": {
      lowLabel: "mid1F#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "フレア": {
      lowLabel: "mid2A",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "99": {
      lowLabel: "mid2A#",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "Fall": {
      lowLabel: "mid1F",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "愛に抱かれて": {
      lowLabel: "mid1F#",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "Gifts": {
      lowLabel: "mid1G",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
    "Wildflower": {
      lowLabel: "mid1E",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/26",
    },
  },

  LiSA: {
    "紅蓮華": {
      lowLabel: "mid1E",
      highLabel: "hiG",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "炎": {
      lowLabel: "mid1G",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "crossing field": {
      lowLabel: "mid2A",
      highLabel: "hiD#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "Rising Hope": {
      lowLabel: "mid2A#",
      highLabel: "hiF#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "Catch the Moment": {
      lowLabel: "mid1F#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "ADAMAS": {
      lowLabel: "mid1F",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "unlasting": {
      lowLabel: "mid1G",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "シルシ": {
      lowLabel: "mid1D#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "oath sign": {
      lowLabel: "mid2A#",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "往け": {
      lowLabel: "mid1G#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "明け星": {
      lowLabel: "mid2A#",
      highLabel: "hiC#",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "HADASHi NO STEP": {
      lowLabel: "mid1G",
      highLabel: "hiD",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "REALiZE": {
      lowLabel: "mid1D#",
      highLabel: "hiF",
      rangeVerified: true,
      rangeSource: "https://keytube.net/artist/detail/22",
    },
    "ブラックボックス": {
      lowLabel: "mid1E",
      highLabel: "hiE",
      rangeVerified: true,
      rangeSource: "https://keytube.net/song/detail/164338",
    },
  },
}

export const EXTRA_SONGS =
  Object.entries(EXTRA_CATALOG).flatMap(
    ([artist, titles]) =>
      titles.map(title => ({
        title,
        artist,
        rangeVerified: false,
        ...(EXTRA_RANGE_DATA[artist]?.[title] ?? {}),
      }))
  )
